name: applicazione_mental_coach
description: "KAIX - Mobile app for athletes and sports teams mental wellness"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.8
  go_router: ^14.3.0
  flutter_svg: ^2.0.7
  lottie: ^3.1.2
  rive: ^0.13.1
  
  # State Management
  provider: ^6.1.2
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  
  # HTTP & API
  http: ^1.2.2
  dio: ^5.7.0
  web_socket_channel: ^3.0.1
  
  # Storage & Caching
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Health & Wearables
  health: ^13.1.4
  permission_handler: ^11.3.1
  
  # Firebase & Push Notifications
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3
  
  # Audio & Voice
  speech_to_text: ^7.0.0
  flutter_tts: ^4.1.0
  record: ^6.1.1
  
  # Utilities
  uuid: ^4.5.1
  intl: ^0.20.0
  crypto: ^3.0.5
  logger: ^2.4.0
  url_launcher: ^6.3.1
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2
  
  # JSON & Serialization
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  
  # Testing & Development
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Linting & Code Quality
  flutter_lints: ^4.0.0
  very_good_analysis: ^6.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  
  # Testing
  mockito: ^5.4.4
  fake_async: ^1.3.1
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
  generate: true # For l10n generation

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/avatars/
    
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
